export type BrandRole =
  | 'green'
  | 'blue'
  | 'orange'
  | 'purple'
  | 'yellow'
  | 'teal'
  | 'pink'
  | 'cyan';
export type CreatureCell = readonly [number, number];

export const roleColorVars: Record<BrandRole, string> = {
  green: 'var(--role-green)',
  blue: 'var(--role-blue)',
  orange: 'var(--role-orange)',
  purple: 'var(--role-purple)',
  yellow: 'var(--role-yellow)',
  teal: 'var(--role-teal)',
  pink: 'var(--role-pink)',
  cyan: 'var(--role-cyan)',
};

export const roleEyeVars: Record<BrandRole, string> = {
  green: 'var(--role-green-deep)',
  blue: 'color-mix(in srgb, var(--role-blue) 62%, var(--ink))',
  orange: 'color-mix(in srgb, var(--role-orange) 62%, var(--ink))',
  purple: 'color-mix(in srgb, var(--role-purple) 62%, var(--ink))',
  yellow: 'color-mix(in srgb, var(--role-yellow) 62%, var(--ink))',
  teal: 'color-mix(in srgb, var(--role-teal) 62%, var(--ink))',
  pink: 'color-mix(in srgb, var(--role-pink) 62%, var(--ink))',
  cyan: 'color-mix(in srgb, var(--role-cyan) 62%, var(--ink))',
};

export const creatureShapes = {
  clawd: [
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 3],
    [2, 3],
    [4, 3],
  ],
  notch: [
    [1, 0],
    [2, 0],
    [3, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [1, 2],
    [2, 2],
    [3, 2],
    [0, 3],
    [1, 3],
    [3, 3],
    [4, 3],
  ],
  runner: [
    [1, 0],
    [2, 0],
    [3, 0],
    [4, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [5, 1],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 3],
    [3, 3],
    [5, 3],
  ],
  wide: [
    [1, 0],
    [2, 0],
    [3, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [0, 2],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 3],
    [3, 3],
  ],
  tall: [
    [1, 0],
    [1, 1],
    [2, 1],
    [0, 2],
    [1, 2],
    [2, 2],
    [3, 2],
    [1, 3],
    [2, 3],
    [1, 4],
    [2, 4],
  ],
  sprout: [
    [2, 0],
    [1, 1],
    [2, 1],
    [3, 1],
    [0, 2],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 3],
    [2, 3],
    [3, 3],
    [1, 4],
    [3, 4],
  ],
  hopper: [
    [1, 0],
    [2, 0],
    [3, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [1, 2],
    [2, 2],
    [3, 2],
    [1, 3],
    [3, 3],
  ],
  pebble: [
    [2, 0],
    [0, 1],
    [1, 1],
    [2, 1],
    [3, 1],
    [4, 1],
    [0, 2],
    [1, 2],
    [2, 2],
    [3, 2],
    [4, 2],
    [1, 3],
    [2, 3],
    [3, 3],
    [1, 4],
    [3, 4],
  ],
} as const satisfies Record<string, readonly CreatureCell[]>;

export type CreatureShape = keyof typeof creatureShapes;
