steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - '-f'
      - Dockerfile
      - .
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  - name: gcr.io/cloud-builders/docker
    args:
      - tag
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
    id: Rename to Latest

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
    id: Push Latest

  - id: Proxy Install
    name: gcr.io/cloud-builders/npm
    entrypoint: sh
    args:
      - '-c'
      - 'wget https://storage.googleapis.com/cloudsql-proxy/v1.20.2/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy && chmod +x cloud_sql_proxy'
    waitFor: ['-']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

  - name: 'gcr.io/cloud-builders/curl'
    id: Trigger Tests
    entrypoint: /bin/sh
    args:
      - -c
      - |
        if [ "$_SERVICE_NAME" = "saas-web-app" ]; then
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $$GITHUB_TOKEN" \
            https://api.github.com/repos/unifyai/console/dispatches \
            -d '{"event_type": "cloudbuild-complete", "client_payload": {"sha": "$COMMIT_SHA"}}'
        else
          echo "Skipping workflow dispatch for service $_SERVICE_NAME"
        fi
    secretEnv: ['GITHUB_TOKEN']

images:
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
  - $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:latest
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: saas-web-app-redesign-staging
  _TRIGGER_ID: 43a9d7a2-951c-49f5-af3c-234567890abc
  REPO_NAME: console
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: europe-west3-docker.pkg.dev
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DEVBOT_GITHUB_TOKEN/versions/latest
      env: 'GITHUB_TOKEN'
