/* See: https://docs.unify.ai/api-reference/llm_queries/chat_completions */

export type UnifyChatModelId =
  // replace with available models
  | (string & {});

export interface UnifyChatSettings {
  /* Up to 4 sequences where the API will stop generating further tokens.`.*/
  stop?: string[],

  /* If set, partial message deltas will be sent. Tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message. */
  stream?: boolean,

  /* Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model’s likelihood to repeat the same line verbatim. */
  frequency_penalty?: number,
    
  /* Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token. */
  logit_bias?: {[key: string]: number}

  /* Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the content of message. */
  logprobs?: boolean,
  
  /* An integer between 0 and 20 specifying the number of most likely tokens to return at each token position, each with an associated log probability. logprobs must be set to true if this parameter is used. */
  top_logprobs?: number,

  /* How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep n as 1 to minimize costs. */
  n?: number,

  /* Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model’s likelihood to talk about new topics. */
  presence_penalty?: number,

  /* If specified, the system will make a best effort to sample deterministically, such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend. */
  seed?: number,
  
  /* Whether to enable parallel function calling during tool use. */
  parallel_tool_calls?: boolean,
  
}
