export const providers = {
  anyscale: 'https://storage.googleapis.com/hub-provider-images/anyscale-logo.jpg',
  'perplexity-ai': 'https://storage.googleapis.com/hub-provider-images/perplexity-ai-logo.png',
  'together-ai': 'https://storage.googleapis.com/hub-provider-images/together-ai-logo.png',
  octoai: 'https://storage.googleapis.com/hub-provider-images/octoai-logo.png',
  replicate: 'https://storage.googleapis.com/hub-provider-images/replicate-logo.svg',
  'mistral-ai': 'https://storage.googleapis.com/hub-provider-images/mistral-logo.png',
  openai: 'https://storage.googleapis.com/hub-provider-images/openai-logo.png',
  'fireworks-ai': 'https://storage.googleapis.com/hub-provider-images/fireworks-ai-logo.png',
  'lepton-ai': 'https://storage.googleapis.com/hub-provider-images/lepton-ai-logo.png',
  deepinfra: 'https://storage.googleapis.com/hub-provider-images/deepinfra-logo.svg',
  'aws-bedrock': 'https://storage.googleapis.com/hub-provider-images/aws-bedrock-logo.png',
  anthropic: 'https://storage.googleapis.com/hub-provider-images/anthropic-logo.png',
  groq: 'https://storage.googleapis.com/hub-provider-images/groq-logo.png',
  'vertex-ai': 'https://storage.googleapis.com/hub-provider-images/vertex-ai-logo.png',
  'azure-ai': 'https://storage.googleapis.com/hub-provider-images/azure-ai-logo.png',
  xai: 'https://storage.googleapis.com/hub-provider-images/xai-logo.png',
  deepseek: 'https://storage.googleapis.com/hub-provider-images/deepseek-logo.png',
} as { [key: string]: string };
