export const ASSISTANT_ONBOARDING_FEE = 10;
export const EMAIL_DOMAIN_WITH_AT = "@unify.ai";
export const FALLBACK_DEFAULT_COUNTRY_CODE = "US"; 
export const AVAILABLE_PHONE_COUNTRIES_CODES = "US,GB,CA,FI,NL,PR"