#!/usr/bin/env bash
# =============================================================================
# ci-test-setup.sh — Bootstrap the E2E test environment for CI
# =============================================================================
#
# Generates a minimal .env.local (intentionally omitting cloud credentials so
# all service stubs activate via credential-absence), then starts PostgreSQL,
# Orchestra, and the Console dev server.
#
# Usage:
#   bash scripts/ci-test-setup.sh                  # full setup
#   bash scripts/ci-test-setup.sh --no-seed        # skip seed scenarios
#   bash scripts/ci-test-setup.sh --seed org-basic  # specific seed scenario
#
# Prerequisites:
#   - Docker (for PostgreSQL)
#   - Python 3.12+ with uv (for Orchestra)
#   - Node.js 20+ with npm (for Console)
#   - Orchestra repo at $ORCHESTRA_REPO_PATH (or ../orchestra)
#
# Environment (all optional):
#   ORCHESTRA_REPO_PATH     Path to orchestra repo (default: ../orchestra)
#   ORCHESTRA_PORT          Orchestra port (default: 8000)
#   CONSOLE_PORT            Console port (default: 3000)
#   ORCHESTRA_ADMIN_KEY     Admin key (default: ci-test-admin-key-e2e)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
CONSOLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"

ORCHESTRA_REPO_PATH="${ORCHESTRA_REPO_PATH:-$(cd "$CONSOLE_DIR/../orchestra" 2>/dev/null && pwd -P || echo "")}"
ORCHESTRA_PORT="${ORCHESTRA_PORT:-8000}"
CONSOLE_PORT="${CONSOLE_PORT:-3000}"
PUBSUB_EMULATOR_HOST="${PUBSUB_EMULATOR_HOST:-127.0.0.1:8085}"
PUBSUB_PROJECT_ID="${PUBSUB_PROJECT_ID:-local-test-project}"
ADMIN_KEY="${ORCHESTRA_ADMIN_KEY:-ci-test-admin-key-e2e}"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[ci]${NC} $*"; }
log_success() { echo -e "${GREEN}[ci]${NC} $*"; }
log_error()   { echo -e "${RED}[ci]${NC} $*"; }

# Parse args
NO_SEED=false
SEED_SCENARIO="personal-workspace"
while (( "$#" )); do
  case "$1" in
    --no-seed)  NO_SEED=true; shift ;;
    --seed)     shift; SEED_SCENARIO="${1:-personal-workspace}"; shift ;;
    *)          shift ;;
  esac
done

echo ""
echo "═══════════════════════════════════════════════"
echo "  CI E2E Test Environment Setup"
echo "═══════════════════════════════════════════════"
echo ""

# ── 1. Validate prerequisites ──────────────────────────────────────────

if [[ -z "$ORCHESTRA_REPO_PATH" || ! -f "$ORCHESTRA_REPO_PATH/scripts/local.sh" ]]; then
  log_error "Orchestra repo not found at ${ORCHESTRA_REPO_PATH:-<not set>}"
  log_info "Set ORCHESTRA_REPO_PATH or checkout orchestra alongside console"
  exit 1
fi
log_success "Orchestra repo: $ORCHESTRA_REPO_PATH"

if [[ -f "$SCRIPT_DIR/ensure-sibling-repo-branch.sh" && -n "$ORCHESTRA_REPO_PATH" ]]; then
  bash "$SCRIPT_DIR/ensure-sibling-repo-branch.sh" "$ORCHESTRA_REPO_PATH" orchestra || true
fi

# Propagate the resolved paths to later workflow steps. GitHub Actions runs each
# step in a fresh shell, so a value computed here is invisible to the test-run
# step unless written to $GITHUB_ENV. Without this the test process re-derives
# ORCHESTRA_REPO_PATH from a relative default that is wrong under the CI checkout
# layout (orchestra lives one level deeper), so argon2 password-hash generation
# for seeded email logins fails and every UI login in the suite fails fast.
if [[ -n "${GITHUB_ENV:-}" ]]; then
  echo "ORCHESTRA_REPO_PATH=$ORCHESTRA_REPO_PATH" >> "$GITHUB_ENV"
  echo "PUBSUB_EMULATOR_HOST=$PUBSUB_EMULATOR_HOST" >> "$GITHUB_ENV"
  echo "PUBSUB_PROJECT_ID=$PUBSUB_PROJECT_ID" >> "$GITHUB_ENV"
  if [[ -x "$ORCHESTRA_REPO_PATH/.venv/bin/python" ]]; then
    echo "ORCHESTRA_PYTHON=$ORCHESTRA_REPO_PATH/.venv/bin/python" >> "$GITHUB_ENV"
    log_success "Resolved Orchestra Python: $ORCHESTRA_REPO_PATH/.venv/bin/python"
  fi
fi

if ! command -v docker &>/dev/null; then
  log_error "Docker is not installed (required for PostgreSQL)"
  exit 1
fi

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
  log_error "Python is not installed (required for Orchestra)"
  exit 1
fi

if ! command -v node &>/dev/null; then
  log_error "Node.js is not installed (required for Console)"
  exit 1
fi

# ── 2. Generate .env.local ─────────────────────────────────────────────
#
# Intentionally omit cloud credentials so credential-absence stubs
# activate automatically. Services that get stubbed:
#   - LiveKit (calls)        — no LIVEKIT_URL/API_KEY/API_SECRET
#   - GCS (file storage)     — no GOOGLE_APPLICATION_CREDENTIALS
#   - Pub/Sub (live actions) — no COMMS_SERVICE_ACCOUNT_CREDENTIALS
#   - Replicate (photos)     — no REPLICATE_API_KEY
#   - Cartesia/ElevenLabs    — no API keys
#   - Deepgram               — no DEEPGRAM_API_KEY

cat > "$CONSOLE_DIR/.env.local" << EOF
# Auto-generated by ci-test-setup.sh
# No cloud credentials = all service stubs active
NEXTAUTH_SECRET=ci-e2e-test-secret-must-be-at-least-32-characters-long
JWT_SECRET=ci-e2e-test-jwt-secret-must-be-at-least-32-characters
NEXTAUTH_URL=http://localhost:${CONSOLE_PORT}
ORCHESTRA_URL=http://127.0.0.1:${ORCHESTRA_PORT}
ORCHESTRA_ADMIN_KEY=${ADMIN_KEY}
PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST}
PUBSUB_PROJECT_ID=${PUBSUB_PROJECT_ID}
CLOUD_RUN_ORCHESTRA_DB_USER=orchestra
CLOUD_RUN_ORCHESTRA_DB_PASS=orchestra
CLOUD_RUN_ORCHESTRA_HOST=localhost
GOOGLE_ID=ci-dummy-google-id
GOOGLE_SECRET=ci-dummy-google-secret
GITHUB_ID=ci-dummy-github-id
GITHUB_SECRET=ci-dummy-github-secret
EOF

log_success ".env.local created (cloud credentials omitted → stubs active)"

# ── 3. Start PostgreSQL + Orchestra ────────────────────────────────────

log_info "Starting Orchestra stack (PostgreSQL + FastAPI)..."

export ORCHESTRA_ADMIN_KEY="$ADMIN_KEY"
export ORCHESTRA_PORT="$ORCHESTRA_PORT"
export UNIFY_CONSOLE_FRONTEND_URL="http://localhost:${CONSOLE_PORT}"

_orchestra_attempt=0
_orchestra_max_attempts=3
while (( _orchestra_attempt < _orchestra_max_attempts )); do
  if ORCHESTRA_REPO_PATH="$ORCHESTRA_REPO_PATH" bash "$ORCHESTRA_REPO_PATH/scripts/local.sh" start; then
    break
  fi
  ((_orchestra_attempt++)) || true
  if (( _orchestra_attempt >= _orchestra_max_attempts )); then
    log_error "Orchestra failed to start after ${_orchestra_max_attempts} attempts"
    log_info "Check logs: /tmp/orchestra-local-server.log"
    exit 1
  fi
  log_info "Orchestra start failed — retrying ($((_orchestra_attempt + 1))/${_orchestra_max_attempts})..."
  sleep 5
done

log_success "Orchestra ready at http://127.0.0.1:${ORCHESTRA_PORT}"

# Vitest ``@real`` specs call Orchestra directly and need a valid local API key.
DB_CONTAINER="${ORCHESTRA_DB_CONTAINER:-orchestra-local-db}"
VITE_TEST_API_KEY="$(docker exec "$DB_CONTAINER" psql -U orchestra -d orchestra -tAc \
  "SELECT key FROM api_key WHERE organization_id IS NULL ORDER BY id LIMIT 1;" 2>/dev/null | tr -d '[:space:]')"

if [[ -z "$VITE_TEST_API_KEY" ]]; then
  log_error "Could not resolve VITE_TEST_API_KEY from local Orchestra DB"
  exit 1
fi

export ORCHESTRA_URL="http://127.0.0.1:${ORCHESTRA_PORT}"
export VITE_TEST_API_KEY
echo "VITE_TEST_API_KEY=${VITE_TEST_API_KEY}" >> "$CONSOLE_DIR/.env.local"

if [[ -n "${GITHUB_ENV:-}" ]]; then
  echo "ORCHESTRA_URL=http://127.0.0.1:${ORCHESTRA_PORT}" >> "$GITHUB_ENV"
  echo "VITE_TEST_API_KEY=${VITE_TEST_API_KEY}" >> "$GITHUB_ENV"
fi
log_success "Vitest real-integration credentials provisioned"

# ── 4. Start Pub/Sub emulator ─────────────────────────────────────────

log_info "Starting Pub/Sub emulator on ${PUBSUB_EMULATOR_HOST}..."
if [[ -f /tmp/pubsub-ci.pid ]]; then
  stale_pubsub_pid="$(tr -d '\n' < /tmp/pubsub-ci.pid || true)"
  if [[ -n "$stale_pubsub_pid" ]]; then
    kill "$stale_pubsub_pid" 2>/dev/null || true
  fi
fi
pubsub_port="${PUBSUB_EMULATOR_HOST##*:}"
pubsub_pids=$(lsof -t -i ":${pubsub_port}" 2>/dev/null || true)
if [[ -n "$pubsub_pids" ]]; then
  echo "$pubsub_pids" | xargs kill -9 2>/dev/null || true
  sleep 1
fi
if ! command -v gcloud &>/dev/null; then
  log_error "gcloud is required for the Pub/Sub emulator"
  exit 1
fi
# Guarantee the emulator component is functionally present. On CI the helper
# re-adds the Google Cloud apt repo and installs the package; locally it no-ops
# when the emulator is already available.
if [[ "${CI:-}" == "true" ]]; then
  bash "$SCRIPT_DIR/ci-install-pubsub-emulator.sh"
fi
setsid gcloud beta emulators pubsub start \
  --project="$PUBSUB_PROJECT_ID" \
  --host-port="$PUBSUB_EMULATOR_HOST" \
  > /tmp/pubsub-ci.log 2>&1 </dev/null &
PUBSUB_PID=$!
echo "$PUBSUB_PID" > /tmp/pubsub-ci.pid
for _ in {1..60}; do
  if ! kill -0 "$PUBSUB_PID" 2>/dev/null; then
    log_error "Pub/Sub emulator exited before readiness"
    tail -50 /tmp/pubsub-ci.log 2>/dev/null || true
    tail -50 /tmp/pubsub-emulator-apt.log 2>/dev/null || true
    exit 1
  fi
  if curl -s --connect-timeout 1 --max-time 2 "http://${PUBSUB_EMULATOR_HOST}/" &>/dev/null; then
    log_success "Pub/Sub emulator ready at ${PUBSUB_EMULATOR_HOST}"
    break
  fi
  sleep 1
done
if ! kill -0 "$PUBSUB_PID" 2>/dev/null; then
  log_error "Pub/Sub emulator failed to start"
  tail -50 /tmp/pubsub-ci.log 2>/dev/null || true
  tail -50 /tmp/pubsub-emulator-apt.log 2>/dev/null || true
  exit 1
fi

# ── 5. Start Console ──────────────────────────────────────────────────

cd "$CONSOLE_DIR"

# Kill any stale processes on the Console port
if [[ -f /tmp/console-ci.pid ]]; then
  stale_pid="$(tr -d '\n' < /tmp/console-ci.pid || true)"
  if [[ -n "$stale_pid" ]]; then
    kill "$stale_pid" 2>/dev/null || true
  fi
fi
stale_pids=$(lsof -t -i ":${CONSOLE_PORT}" 2>/dev/null || true)
if [[ -n "$stale_pids" ]]; then
  echo "$stale_pids" | xargs kill -9 2>/dev/null || true
  sleep 1
fi

export NEXTAUTH_URL="http://localhost:${CONSOLE_PORT}"
export ORCHESTRA_URL="http://127.0.0.1:${ORCHESTRA_PORT}"
export PUBSUB_EMULATOR_HOST
export PUBSUB_PROJECT_ID
export NEXT_TELEMETRY_DISABLED=1

# Build once, then serve with `next start`. Running E2E against a production
# build instead of `next dev` removes per-route compile-on-demand, which was
# the dominant cost: under `next dev` a cold route hit took 1-2 min (and often
# blew the per-test timeout, surfacing as "flaky" retries). A prod build
# compiles everything up front so every navigation is served in milliseconds.
# Call `next` directly to skip the npm `prebuild` live-stack guard and the
# style check (already enforced by the lint gate).
log_info "Building Console (production)..."
if ! NODE_OPTIONS="--max-old-space-size=6144" npx next build --no-lint > /tmp/console-build.log 2>&1; then
  log_error "Console build failed"
  tail -80 /tmp/console-build.log 2>/dev/null || true
  exit 1
fi
log_success "Console build complete"

log_info "Starting Console on port ${CONSOLE_PORT}..."
mkdir -p "$CONSOLE_DIR/.next/standalone/.next"
cp -r "$CONSOLE_DIR/.next/static" "$CONSOLE_DIR/.next/standalone/.next/static" 2>/dev/null || true
cp -r "$CONSOLE_DIR/public" "$CONSOLE_DIR/.next/standalone/public" 2>/dev/null || true

# The Next.js standalone server (`node server.js`) does NOT read `.env.local` at
# runtime — only `next dev` / `next start` load env files. Running the standalone
# build without exporting the generated secrets leaves NextAuth with no
# `NEXTAUTH_SECRET`, so it throws `MissingSecretError` in production mode and
# every credentials sign-in fails (all authenticated tests then bounce back to
# `/login`). Export the whole generated env into the server process so the
# secrets (NEXTAUTH_SECRET, JWT_SECRET, ORCHESTRA_ADMIN_KEY, OAuth ids, …) and
# any future additions flow through automatically.
set -a
# shellcheck disable=SC1091
. "$CONSOLE_DIR/.env.local"
set +a

# Give the long-lived server process a generous, explicit heap. The standalone
# `node server.js` otherwise inherits the V8 default old-space cap (~2 GB), and
# under a full sharded E2E run (hundreds of SSR renders + API/SSE requests) GC
# pressure near that ceiling makes late-running tests slow down and time out
# even though early tests in the same shard passed. The runner has 16 GB and the
# build has already finished by this point, so 4 GB is comfortably safe.
setsid env \
  PORT="$CONSOLE_PORT" \
  HOSTNAME=0.0.0.0 \
  NODE_OPTIONS="--max-old-space-size=4096" \
  node "$CONSOLE_DIR/.next/standalone/server.js" > /tmp/console-ci.log 2>&1 </dev/null &
CONSOLE_PID=$!
echo "$CONSOLE_PID" > /tmp/console-ci.pid

# `next start` serves as soon as it binds the port; no compile wait needed.
max_attempts=90
attempt=0
while (( attempt < max_attempts )); do
  if ! kill -0 "$CONSOLE_PID" 2>/dev/null; then
    log_error "Console server process exited before readiness"
    log_info "Last 50 lines of Console log:"
    tail -50 /tmp/console-ci.log 2>/dev/null || true
    exit 1
  fi
  if curl -s --connect-timeout 2 --max-time 5 "http://localhost:${CONSOLE_PORT}" &>/dev/null; then
    log_success "Console ready at http://localhost:${CONSOLE_PORT} (${attempt}s)"
    break
  fi
  sleep 1
  ((attempt++)) || true
done

if (( attempt >= max_attempts )); then
  log_error "Console failed to start within ${max_attempts} seconds"
  log_info "Last 50 lines of Console log:"
  tail -50 /tmp/console-ci.log 2>/dev/null || true
  exit 1
fi

# ── 6. Seed test data (optional) ──────────────────────────────────────
#
# E2E tests create their own users/assistants in beforeAll, so seeding
# is optional. It can help pre-warm the database schema validation and
# ensure voice presets exist.

if [[ "$NO_SEED" == "false" ]]; then
  log_info "Seeding: $SEED_SCENARIO"
  export ORCHESTRA_DB_CONTAINER="orchestra-local-db"
  export NEXT_PUBLIC_BASE_URL="http://localhost:${CONSOLE_PORT}"
  export ORCHESTRA_REPO_PATH

  # Note: uses helpers/seeds path (not src/tests/seeds)
  if npx tsx src/tests/helpers/seeds/run.ts "$SEED_SCENARIO" 2>/dev/null; then
    log_success "Seed scenario '$SEED_SCENARIO' completed"
  else
    log_info "WARN: Seed failed (tests create their own data, so this is non-fatal)"
  fi
fi

# ── Done ───────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════"
log_success "CI E2E Test Environment Ready"
echo "═══════════════════════════════════════════════"
echo ""
echo "  Console:      http://localhost:${CONSOLE_PORT}"
echo "  Orchestra:    http://127.0.0.1:${ORCHESTRA_PORT}/v0"
echo "  PostgreSQL:   orchestra-local-db (Docker)"
echo ""
echo "  Stubs active: LiveKit, GCS, Pub/Sub, Replicate,"
echo "                Cartesia, ElevenLabs, Deepgram, OpenAI TTS"
echo ""
echo "  Run tests:    npx playwright test src/tests/assistants/"
echo ""
