#!/usr/bin/env bash
# =============================================================================
# ci-test-setup.sh — Bootstrap the E2E test environment for CI
# =============================================================================
#
# Generates a minimal .env.local (intentionally omitting cloud credentials so
# all service stubs activate via credential-absence), then starts PostgreSQL,
# Orchestra, and the Console dev server.
#
# Usage:
#   bash scripts/ci-test-setup.sh                  # full setup
#   bash scripts/ci-test-setup.sh --no-seed        # skip seed scenarios
#   bash scripts/ci-test-setup.sh --seed org-basic  # specific seed scenario
#
# Prerequisites:
#   - Docker (for PostgreSQL)
#   - Python 3.12+ with Poetry (for Orchestra)
#   - Node.js 20+ with npm (for Console)
#   - Orchestra repo at $ORCHESTRA_REPO_PATH (or ../orchestra)
#
# Environment (all optional):
#   ORCHESTRA_REPO_PATH     Path to orchestra repo (default: ../orchestra)
#   ORCHESTRA_PORT          Orchestra port (default: 8000)
#   CONSOLE_PORT            Console port (default: 3000)
#   ORCHESTRA_ADMIN_KEY     Admin key (default: ci-test-admin-key-e2e)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
CONSOLE_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"

ORCHESTRA_REPO_PATH="${ORCHESTRA_REPO_PATH:-$(cd "$CONSOLE_DIR/../orchestra" 2>/dev/null && pwd -P || echo "")}"
ORCHESTRA_PORT="${ORCHESTRA_PORT:-8000}"
CONSOLE_PORT="${CONSOLE_PORT:-3000}"
ADMIN_KEY="${ORCHESTRA_ADMIN_KEY:-ci-test-admin-key-e2e}"

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[ci]${NC} $*"; }
log_success() { echo -e "${GREEN}[ci]${NC} $*"; }
log_error()   { echo -e "${RED}[ci]${NC} $*"; }

# Parse args
NO_SEED=false
SEED_SCENARIO="personal-workspace"
while (( "$#" )); do
  case "$1" in
    --no-seed)  NO_SEED=true; shift ;;
    --seed)     shift; SEED_SCENARIO="${1:-personal-workspace}"; shift ;;
    *)          shift ;;
  esac
done

echo ""
echo "═══════════════════════════════════════════════"
echo "  CI E2E Test Environment Setup"
echo "═══════════════════════════════════════════════"
echo ""

# ── 1. Validate prerequisites ──────────────────────────────────────────

if [[ -z "$ORCHESTRA_REPO_PATH" || ! -f "$ORCHESTRA_REPO_PATH/scripts/local.sh" ]]; then
  log_error "Orchestra repo not found at ${ORCHESTRA_REPO_PATH:-<not set>}"
  log_info "Set ORCHESTRA_REPO_PATH or checkout orchestra alongside console"
  exit 1
fi
log_success "Orchestra repo: $ORCHESTRA_REPO_PATH"

# Propagate the resolved paths to later workflow steps. GitHub Actions runs each
# step in a fresh shell, so a value computed here is invisible to the test-run
# step unless written to $GITHUB_ENV. Without this the test process re-derives
# ORCHESTRA_REPO_PATH from a relative default that is wrong under the CI checkout
# layout (orchestra lives one level deeper), so argon2 password-hash generation
# for seeded email logins fails and every UI login in the suite fails fast.
if [[ -n "${GITHUB_ENV:-}" ]]; then
  echo "ORCHESTRA_REPO_PATH=$ORCHESTRA_REPO_PATH" >> "$GITHUB_ENV"
  if command -v poetry &>/dev/null; then
    poetry_venv="$(cd "$ORCHESTRA_REPO_PATH" && poetry env info -p 2>/dev/null || true)"
    if [[ -n "$poetry_venv" && -x "$poetry_venv/bin/python" ]]; then
      echo "ORCHESTRA_PYTHON=$poetry_venv/bin/python" >> "$GITHUB_ENV"
      log_success "Resolved Orchestra Python: $poetry_venv/bin/python"
    fi
  fi
fi

if ! command -v docker &>/dev/null; then
  log_error "Docker is not installed (required for PostgreSQL)"
  exit 1
fi

if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
  log_error "Python is not installed (required for Orchestra)"
  exit 1
fi

if ! command -v node &>/dev/null; then
  log_error "Node.js is not installed (required for Console)"
  exit 1
fi

# ── 2. Generate .env.local ─────────────────────────────────────────────
#
# Intentionally omit cloud credentials so credential-absence stubs
# activate automatically. Services that get stubbed:
#   - LiveKit (calls)        — no LIVEKIT_URL/API_KEY/API_SECRET
#   - GCS (file storage)     — no GOOGLE_APPLICATION_CREDENTIALS
#   - Pub/Sub (live actions) — no COMMS_SERVICE_ACCOUNT_CREDENTIALS
#   - Replicate (photos)     — no REPLICATE_API_KEY
#   - Cartesia/ElevenLabs    — no API keys
#   - Deepgram               — no DEEPGRAM_API_KEY

cat > "$CONSOLE_DIR/.env.local" << EOF
# Auto-generated by ci-test-setup.sh
# No cloud credentials = all service stubs active
NEXTAUTH_SECRET=ci-e2e-test-secret-must-be-at-least-32-characters-long
JWT_SECRET=ci-e2e-test-jwt-secret-must-be-at-least-32-characters
NEXTAUTH_URL=http://localhost:${CONSOLE_PORT}
ORCHESTRA_URL=http://127.0.0.1:${ORCHESTRA_PORT}
ORCHESTRA_ADMIN_KEY=${ADMIN_KEY}
CLOUD_RUN_ORCHESTRA_DB_USER=orchestra
CLOUD_RUN_ORCHESTRA_DB_PASS=orchestra
CLOUD_RUN_ORCHESTRA_HOST=localhost
GOOGLE_ID=ci-dummy-google-id
GOOGLE_SECRET=ci-dummy-google-secret
GITHUB_ID=ci-dummy-github-id
GITHUB_SECRET=ci-dummy-github-secret
EOF

log_success ".env.local created (cloud credentials omitted → stubs active)"

# ── 3. Start PostgreSQL + Orchestra ────────────────────────────────────

log_info "Starting Orchestra stack (PostgreSQL + FastAPI)..."

export ORCHESTRA_ADMIN_KEY="$ADMIN_KEY"
export ORCHESTRA_PORT="$ORCHESTRA_PORT"
export UNIFY_CONSOLE_FRONTEND_URL="http://localhost:${CONSOLE_PORT}"

if ! ORCHESTRA_REPO_PATH="$ORCHESTRA_REPO_PATH" bash "$ORCHESTRA_REPO_PATH/scripts/local.sh" start; then
  log_error "Orchestra failed to start"
  log_info "Check logs: /tmp/orchestra-local-server.log"
  exit 1
fi

log_success "Orchestra ready at http://127.0.0.1:${ORCHESTRA_PORT}"

# ── 4. Start Console ──────────────────────────────────────────────────

cd "$CONSOLE_DIR"

# Kill any stale processes on the Console port
stale_pids=$(lsof -t -i ":${CONSOLE_PORT}" 2>/dev/null || true)
if [[ -n "$stale_pids" ]]; then
  echo "$stale_pids" | xargs kill -9 2>/dev/null || true
  sleep 1
fi

export NEXTAUTH_URL="http://localhost:${CONSOLE_PORT}"
export ORCHESTRA_URL="http://127.0.0.1:${ORCHESTRA_PORT}"
export NEXT_TELEMETRY_DISABLED=1

# Build once, then serve with `next start`. Running E2E against a production
# build instead of `next dev` removes per-route compile-on-demand, which was
# the dominant cost: under `next dev` a cold route hit took 1-2 min (and often
# blew the per-test timeout, surfacing as "flaky" retries). A prod build
# compiles everything up front so every navigation is served in milliseconds.
# Call `next` directly to skip the npm `prebuild` live-stack guard and the
# style check (already enforced by the lint gate).
log_info "Building Console (production)..."
if ! NODE_OPTIONS="--max-old-space-size=6144" npx next build --no-lint > /tmp/console-build.log 2>&1; then
  log_error "Console build failed"
  tail -80 /tmp/console-build.log 2>/dev/null || true
  exit 1
fi
log_success "Console build complete"

log_info "Starting Console on port ${CONSOLE_PORT}..."
nohup npx next start -p "$CONSOLE_PORT" -H 0.0.0.0 > /tmp/console-ci.log 2>&1 &
CONSOLE_PID=$!
echo "$CONSOLE_PID" > /tmp/console-ci.pid

# `next start` serves as soon as it binds the port; no compile wait needed.
max_attempts=90
attempt=0
while (( attempt < max_attempts )); do
  if curl -s --connect-timeout 2 --max-time 5 "http://localhost:${CONSOLE_PORT}" &>/dev/null; then
    log_success "Console ready at http://localhost:${CONSOLE_PORT} (${attempt}s)"
    break
  fi
  sleep 1
  ((attempt++)) || true
done

if (( attempt >= max_attempts )); then
  log_error "Console failed to start within ${max_attempts} seconds"
  log_info "Last 50 lines of Console log:"
  tail -50 /tmp/console-ci.log 2>/dev/null || true
  exit 1
fi

# ── 5. Seed test data (optional) ──────────────────────────────────────
#
# E2E tests create their own users/assistants in beforeAll, so seeding
# is optional. It can help pre-warm the database schema validation and
# ensure voice presets exist.

if [[ "$NO_SEED" == "false" ]]; then
  log_info "Seeding: $SEED_SCENARIO"
  export ORCHESTRA_DB_CONTAINER="orchestra-local-db"
  export NEXT_PUBLIC_BASE_URL="http://localhost:${CONSOLE_PORT}"
  export ORCHESTRA_REPO_PATH

  # Note: uses helpers/seeds path (not src/tests/seeds)
  if npx tsx src/tests/helpers/seeds/run.ts "$SEED_SCENARIO" 2>/dev/null; then
    log_success "Seed scenario '$SEED_SCENARIO' completed"
  else
    log_info "WARN: Seed failed (tests create their own data, so this is non-fatal)"
  fi
fi

# ── Done ───────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════"
log_success "CI E2E Test Environment Ready"
echo "═══════════════════════════════════════════════"
echo ""
echo "  Console:      http://localhost:${CONSOLE_PORT}"
echo "  Orchestra:    http://127.0.0.1:${ORCHESTRA_PORT}/v0"
echo "  PostgreSQL:   orchestra-local-db (Docker)"
echo ""
echo "  Stubs active: LiveKit, GCS, Pub/Sub, Replicate,"
echo "                Cartesia, ElevenLabs, Deepgram, OpenAI TTS"
echo ""
echo "  Run tests:    npx playwright test src/tests/assistants/"
echo ""
