import { NextRequest, NextResponse } from "next/server";
import { cartesiaClient } from "@/lib/cartesia";
import { SupportedLanguage } from "@cartesia/cartesia-js/api";
// import { Buffer } from 'node:buffer'; // Not strictly needed if we use Uint8Array and ArrayBuffer directly

interface TTSRequestBody {
    cartesiaVoiceId: string;
    text: string;
    language: SupportedLanguage | undefined;
}

export async function POST(request: NextRequest) {
    try {
        const body = await request.json() as TTSRequestBody;
        const { cartesiaVoiceId, text, language } = body;

        if (!cartesiaVoiceId || !text || !language) {
            return NextResponse.json({ detail: "Missing required fields for TTS: cartesiaVoiceId, text, and language." }, { status: 400 });
        }

        const ttsParams = {
            modelId: "sonic-2" as const, 
            transcript: text,
            voice: {
                mode: "id" as const,
                id: cartesiaVoiceId,
            },
            language: language,
            outputFormat: { 
                container: "wav" as const, 
                encoding: "pcm_s16le" as const,
                sampleRate: 24000,
            }
        };

        const audioStreamOrBuffer = await cartesiaClient.tts.bytes(ttsParams);
        
        let finalArrayBuffer: ArrayBuffer;

        if (Symbol.asyncIterator in audioStreamOrBuffer && typeof (audioStreamOrBuffer as any)[Symbol.asyncIterator] === 'function') {
            // It's an AsyncIterable
            console.log("[API /voices/tts] Processing as AsyncIterable...");
            const chunks: Uint8Array[] = [];
            const stream = audioStreamOrBuffer as AsyncIterable<Uint8Array>; // Cast to be sure
            for await (const chunk of stream) {
                chunks.push(chunk);
            }
            
            if (chunks.length === 0) {
                console.warn("[API /voices/tts] No audio data received from Cartesia stream for request:", body);
                return NextResponse.json({ detail: "No audio data generated by TTS service (empty stream)." }, { status: 500 });
            }

            let totalLength = 0;
            chunks.forEach(chunk => totalLength += chunk.length);
            const concatenatedUint8Array = new Uint8Array(totalLength);
            let offset = 0;
            chunks.forEach(chunk => {
                concatenatedUint8Array.set(chunk, offset);
                offset += chunk.length;
            });
            finalArrayBuffer = concatenatedUint8Array.buffer;

        } else if (audioStreamOrBuffer instanceof ArrayBuffer) {
            // It's directly an ArrayBuffer
            console.log("[API /voices/tts] Processing as direct ArrayBuffer...");
            finalArrayBuffer = audioStreamOrBuffer;
            if (finalArrayBuffer.byteLength === 0) {
                console.warn("[API /voices/tts] Received empty ArrayBuffer from Cartesia for request:", body);
                return NextResponse.json({ detail: "No audio data generated by TTS service (empty buffer)." }, { status: 500 });
            }
        } else {
            console.error("[API /voices/tts] Unexpected type from Cartesia tts.bytes:", typeof audioStreamOrBuffer, audioStreamOrBuffer);
            return NextResponse.json({ detail: "Unexpected response type from TTS service." }, { status: 500 });
        }
        
        return new NextResponse(finalArrayBuffer, {
            status: 200,
            headers: { 
                "Content-Type": "audio/wav",
            },
        });

    } catch (error: any) {
        console.error("[API /voices/tts] Catch block error:", error);
        let errorMessage = "Failed to generate TTS. Unknown error.";
        let errorStatus = 500;

        if (error.response && typeof error.response.json === 'function') {
            try {
                const errData = await error.response.json();
                errorMessage = `Cartesia API error: ${errData.message || errData.detail || JSON.stringify(errData)}`;
                errorStatus = error.response.status || 500;
            } catch (e) { /* ignore parse error */ }
        } else if (error.message) {
            errorMessage = `Failed to generate TTS: ${error.message}`;
        }
        
        return NextResponse.json({ detail: errorMessage }, { status: errorStatus });
    }
}